# Changes made to this config file will be overwritten by the application on shutdown
# If you want to change anything, first shutdown the application, adjust the settings and start the application again
# Any changes made to this config file can have an impact on performance or break the application
# If you want to reset the values to default, delete this file or start the application with the -R argument
Local-Settings:
  Window:
    # If set to false window can no longer be resized
    Window-Resizable: true
    # Default width and height for the application window
    Window-Default-Width: 1280
    Window-Default-Height: 720
  Logging:
    # Logger Settings
    # higher log levels include everything from lower log levels
    # Log - Levels:
    # 0 --> logger turned off
    # 1 --> logger displays only fatal errors
    # 2 --> logger displays normal errors
    # 3 --> logger displays warnings
    # 4 --> logger displays info (DEFAULT)
    # 5 --> logger displays debug messages (may impact performance, don't use this except if you know what you are doing)
    # 6 --> logger displays everything that happens internally (may impact performance, don't use this except if you know what you are doing)
    Log-Level: 4
    Log-File:
      # If the application log should be written to a log file
      # Enabling, this can impact performance
      Enabled: false
      # If set to true, all log messages will be written to the log file regardless of Log-Level above
      # If set to false, only log messages with the above-specified Log-Level will be written to the log file
      Log-Level-All: true
      # Set how many log files are allowed to exist, before the application starts overwriting the oldest one
      # a higher number will take up more disk space, especially if a high log level is set
      # Suggested range 1-10
      Max-Files: 1
  User-Preferences:
    # Default directory to open when selecting files
    # You can change this as you like, but it will also be updated automatically based on the last pick:
    # Example: last picked animation -> /example/directory/example-animation.mp4 will open /example/directory/ the next time you select an animation
    # %user.home% refers to the users home directory
    Default-Selection-Dir: "%user.home%"
    # If the app should display a short form status bar on the main app window
    Display-Status-Bar: false
    # If the animation should automatically start playing after uploading finished
    Auto-Play-After-Upload: true
  Network:
    # Toggles automatic IPv4 check that is performed when changing the cube IPv4
    # If disabled, connection may fail on the next remote update attempt
    Check-IPv4: true
    # Network task related settings
    Tasks:
      # tasks that are executed periodically
      Periodic:
        # Delay between status requests
        Status-Request-Clock:
          # Periodically performed requests to ensure animation-list is up-to-date and reconnection is detected reliably
          # This task runs regardless of user activity
          Passive: 5.0
          # Periodically performed request to ensure status dialog and status bar are up-to-date
          # This task only runs if either of the above-mentioned widgets is active
          Active: 1.0
        # Minimum delay between network packets (Seconds)
        # Increasing this number may help if you're experiencing issues with network connection
        Network-Communication-Clock: 0.01