LED-Cube-Control-Panel:
  # General Settings for the app
  General:
    # Settings Related to Dark- / Light-Mode
    Dark-Mode:
      # Enable Dark-Mode ? || false = Light-Mode
      Enabled: false
      # Color Palette used for Dark-Mode
      Dark-Mode-Color:
        Primary: "#121212"
        Secondary: "#FFFFFF"
      # Color Palette used for Light-Mode
      Light-Mode-Color:
        Primary: "#FFFFFFF"
        Secondary: "#000000"
    # 'Technical' settings related to the window itself
    Window:
      # Window title displayed in the top bar
      Title: "LED-Cube Control Panel %VERSION%"
      # The initial resolution the window spawns as
      Initial-Resolution:
        # If set to false window can no longer be resized
        # They can still be adjusted with the width and height settings below
        resizable: true
        width: 1080
        height: 720
      # The location on the screen the window will spawn once the app is started
      Initial-Spawn-Location:
        # If center option is set to true the window will always spawn in the middle of the current screen
        # X- and Y Settings below are ignored in that case
        center: true
        x: 500
        y: 500
  # Settings related to Startup
  Startup:
    # If the app should display a fake loading bar on startup (Easter egg)
    Enable-Fake-Loading-Bar: false